/**
 * Action types
 */
export const MAP_STATE_WITH_STORE = 'MAP_STATE_WITH_STORE';
export const INPUT_CHANGE = 'INPUT_CHANGE';
export const PASSWORD_INPUT_CHANGE = 'PASSWORD_INPUT_CHANGE';
export const CONFIRM_PASSWORD_INPUT_CHANGE = 'CONFIRM_PASSWORD_INPUT_CHANGE';
